from application_sdk.common.utils import read_sql_files

queries = read_sql_files(queries_prefix="app/queries")

# Queries
TABLES_CHECK_SQL = queries["TABLES_CHECK"]
TABLES_CHECK_TEMP_TABLE_REGEX_SQL = queries["TABLES_CHECK_TEMP_TABLE_REGEX"]

TEST_AUTHENTICATION_SQL = queries["TEST_AUTHENTICATION"]

FILTER_METADATA_SQL = queries["FILTER_METADATA"]

### Extraction Queries
DATABASE_EXTRACTION_SQL = queries["DATABASE_EXTRACTION"]

SCHEMA_EXTRACTION_SQL = queries["SCHEMA_EXTRACTION"]

TABLE_EXTRACTION_SQL = queries["TABLE_EXTRACTION"]
TABLE_EXTRACTION_TEMP_TABLE_REGEX_SQL = queries["TABLE_EXTRACTION_TEMP_TABLE_REGEX"]

COLUMN_EXTRACTION_SQL = queries["COLUMN_EXTRACTION"]
COLUMN_EXTRACTION_TEMP_TABLE_REGEX_SQL = queries["COLUMN_EXTRACTION_TEMP_TABLE_REGEX"]

PROCEDURE_EXTRACTION_SQL = queries["PROCEDURE_EXTRACTION"]
GET_CLIENT_VERSION_SQL = queries["GET_CLIENT_VERSION"]
